version: '2.4'

networks:
    hospital:
        name: hospital_test

services:
  redis1:
    image: 'redis:latest'
    container_name: redis.hospital1.project.com
    command: redis-server --requirepass hospital1redis
    ports:
      - "6379:6379"
    networks:
      - hospital

  redis2:
    image: 'redis:latest'
    container_name: redis.hospital2.project.com
    command: redis-server --requirepass hospital2redis
    ports:
      - "6380:6379"
    networks:
      - hospital

  # redis3:
  #   image: 'redis:latest'
  #   container_name: redis.hospital3.project.com
  #   command: redis-server --requirepass hospital3redis
  #   ports:
  #     - "6381:6379"
  #   networks:
  #     - hospital